name: Bug Report
description: Report a bug in Kagarr
labels: ['bug', 'triage']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search open and closed issues before filing a new one.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to Settings > Indexers
      2. Add a new Newznab indexer
      3. Click Test
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: Please provide your environment details.
    value: |
        - OS:
        - Kagarr Version:
        - Docker Install: Yes/No
        - Browser (if UI related):
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: |
      Please provide relevant log output. Logs are located in your data directory under `logs/kagarr.log`.
      Tip: You can attach log files by dragging them into this area.
  validations:
    required: false
