name: Feature Request
description: Suggest an idea for Kagarr
labels: ['enhancement', 'triage']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search open and closed issues before filing a new request.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Any other context, screenshots, or references that would help.
      Tip: You can attach images by dragging them into this area.
  validations:
    required: false
