<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="NLog" Version="6.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kagarr.Core\Kagarr.Core.csproj" />
    <ProjectReference Include="..\Kagarr.Http\Kagarr.Http.csproj" />
  </ItemGroup>
</Project>
